### ISSUE TITLE
requirements not found

### ISSUE THREAD

**Issue by perymerdeka** [Charvit123/errorneous_cs#2]
hi, I Try to Running This Project following README.md but I Stuck in this command `pip3 install requirements.txt` because the file was not found

**Comment by sb011** [comment]
> hi, I Try to Running This Project following README.md but I Stuck in this command `pip3 install requirements.txt` because the file was not found

we will,
we are working on this project for university submission, soon we will upload.

**Comment by perymerdeka** [comment]
> > hi, I Try to Running This Project following README.md but I Stuck in this command `pip3 install requirements.txt` because the file was not found
> 
> we will,
> we are working on this project for university submission, soon we will upload.

thank you
